version: "3.6"

services:
  api:
    build: ./backend
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@db/covid
      #   This is our random secret key for the JWT encoding for developmemnt purposes, in production it will be kept hidden
      SECRET_KEY: askdjfh28371p8hdalsfha108947
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app/app
      - ./backend/migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: covid
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
